name: Preview Deploy to Vercel

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: pnpm@10.5.2+sha512.da9dc28cd3ff40d0592188235ab25d3202add8a207afbedc682220e4a0029ffbff4562102b9e6e46b4e3f9e8bd53e6d05de48544b0c57d4b0179e22c76d1199b
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel environment (preview)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel pull --yes --environment=preview --token "$VERCEL_TOKEN"

      - name: Build project (preview)
        run: vercel build

      - name: Deploy to Vercel (preview)
        id: vercel-preview-deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          DEPLOY_URL=$(vercel deploy --prebuilt --token "$VERCEL_TOKEN")
          echo "deployment_url=$DEPLOY_URL" >> $GITHUB_OUTPUT

      - name: Output deployment URL
        run: echo "Preview deployed to ${{ steps.vercel-preview-deploy.outputs.deployment_url }}"


